---
language: ruby

dist: trusty
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.5.3

script: './.travis.sh'
jobs:
  include:
    -
      if: branch = master
      stage: Patch Version Release
      script: ./release.sh
